In [37]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from pathlib import Path

In [80]:
df = pd.read_json (r'Data/train/train.json')

In [81]:
df['path'] = df['image'].map(lambda x: Path('../malaria/')/ x['pathname'][1:])

In [82]:
df.head()

,image,objects,path
0,{'checksum': '676bb8e86fc2dbf05dd97d51a64ac0af...,"[{'category': 'uninfected', 'bbx': {'x1': 1440...",..\malaria\images\8d02117d-6c71-4e47-b50a-6cc8...
1,{'checksum': '1225a18efce159eddf7b0e80e0ea642c...,"[{'category': 'uninfected', 'bbx': {'x1': 735,...",..\malaria\images\10be6380-cbbb-4886-8b9e-ff56...
2,{'checksum': '3eaf840523c30fdf38897ffa01e194eb...,"[{'category': 'uninfected', 'bbx': {'x1': 1027...",..\malaria\images\6b14c855-8561-417c-97a4-63fa...
3,{'checksum': '8a111dffacfa433029492780b9535091...,"[{'category': 'uninfected', 'bbx': {'x1': 1421...",..\malaria\images\13099edb-35d9-438f-b093-2cf2...
4,{'checksum': 'ccef403e971460b86444cca669e68ca1...,"[{'category': 'uninfected', 'bbx': {'x1': 688,...",..\malaria\images\2559636b-f01a-4414-93da-210c...

In [91]:
train = pd.DataFrame(columns=('path','category','x1','x2','y1','y2'))

In [132]:
for i in range(len(df)):
    path = df['path'][i]
    objects = df['objects'][i]
    for j in range(len(objects)):
        train=train.append(pd.DataFrame({'path':[path],
                                         'category':objects[j]['category'],
                                         'x1':objects[j]['bbx']['x1'],
                                         'x2':objects[j]['bbx']['x2'],
                                         'y1':objects[j]['bbx']['y1'],
                                         'y2':objects[j]['bbx']['y2']}),ignore_index=True)

In [135]:
train.to_csv (r'Data/train/train_df.csv', index = None)

In [133]:
train.head()

,path,category,x1,x2,y1,y2
0,..\malaria\images\8d02117d-6c71-4e47-b50a-6cc8...,uninfected,1440,1540,1057,1158
1,..\malaria\images\8d02117d-6c71-4e47-b50a-6cc8...,uninfected,1303,1403,868,971
2,..\malaria\images\8d02117d-6c71-4e47-b50a-6cc8...,uninfected,900,1008,578,689
3,..\malaria\images\8d02117d-6c71-4e47-b50a-6cc8...,uninfected,611,713,304,408
4,..\malaria\images\8d02117d-6c71-4e47-b50a-6cc8...,uninfected,881,1003,198,312

In [137]:
#### test data ####


df = pd.read_json (r'Data/test/test.json')
df['path'] = df['image'].map(lambda x: Path('../malaria/')/ x['pathname'][1:])
df.head()

,image,objects,path
0,{'checksum': 'eea3bfd6a929bcb06f9786667cd3fbb2...,"[{'category': 'uninfected', 'bbx': {'x1': 1744...",..\malaria\images\41be1bd3-0d31-4881-bf1f-3ccd...
1,{'checksum': '2d85fc8ffdb875bb569878243437e4f5...,"[{'category': 'uninfected', 'bbx': {'x1': 1632...",..\malaria\images\64985a1e-16bb-4016-a01c-c21a...
2,{'checksum': 'f7c02b6247f3ccfcd4a22c1f06e0c72c...,"[{'category': 'uninfected', 'bbx': {'x1': 960,...",..\malaria\images\c70894fa-50e8-4eed-a5a8-159a...
3,{'checksum': '50634ef166ae993b4562b96f315ff6db...,"[{'category': 'uninfected', 'bbx': {'x1': 776,...",..\malaria\images\abb72ce2-4193-4dd3-a34c-61c2...
4,{'checksum': '74dd777a74e5a4b24aaee574a99e1459...,"[{'category': 'uninfected', 'bbx': {'x1': 1054...",..\malaria\images\8db76867-671a-4488-a7b6-991e...

In [138]:
test = pd.DataFrame(columns=('path','category','x1','x2','y1','y2'))

In [140]:
for i in range(len(df)):
    path = df['path'][i]
    objects = df['objects'][i]
    for j in range(len(objects)):
        test=test.append(pd.DataFrame({'path':[path],
                                         'category':objects[j]['category'],
                                         'x1':objects[j]['bbx']['x1'],
                                         'x2':objects[j]['bbx']['x2'],
                                         'y1':objects[j]['bbx']['y1'],
                                         'y2':objects[j]['bbx']['y2']}),ignore_index=True)

In [141]:
test.to_csv (r'Data/test/test_df.csv', index = None)

In [142]:
test.head()

,path,category,x1,x2,y1,y2
0,..\malaria\images\41be1bd3-0d31-4881-bf1f-3ccd...,uninfected,1744,1883,576,708
1,..\malaria\images\41be1bd3-0d31-4881-bf1f-3ccd...,uninfected,1249,1373,863,977
2,..\malaria\images\41be1bd3-0d31-4881-bf1f-3ccd...,uninfected,1573,1711,210,335
3,..\malaria\images\41be1bd3-0d31-4881-bf1f-3ccd...,uninfected,1124,1253,1017,1142
4,..\malaria\images\41be1bd3-0d31-4881-bf1f-3ccd...,uninfected,1655,1763,572,695